.\" Copyright (c) 2011-2015 Univa
.\" Copyright (c) 2010 Univa UD

.TH "get-node-software-profile-name" "8" "6.2" "Univa" "UniCloud"
.SH "NAME"
.LP
get-node-software-profile-name - Get the software profile name of the given node.
.SH "SYNTAX"
.LP
\fBget-node-software-profile-name --node=\fINODENAME\fB
.SH "DESCRIPTION"
.LP
The get-node-software-profile-name tool returns the software profile name of a given node.
.LP
.SH "OPTIONS"
.LP
.TP
\fB--node=\fINODENAME
Node associated with software profile
.LP
.SH "Common UniCloud Options"
.LP
.TP
\fB-h, --help
show this help message and exit.
.TP
\fB-?
show this help message and exit.
.TP
\fB-v
print version and exit.
.TP
\fB-d \fPCONSOLELOGLEVEL\fB, --debug=\fPCONSOLELOGLEVEL
set debug level; valid values are: critical, error, warning, info, debug
.TP
\fB--username=\fPUSERNAME
Credential to use when not running as root on the Installer.
.TP
\fB--password=\fPPASSWORD
Credential to use when not running as root on the Installer.
.\".SH "EXAMPLES"
.\".LP
.SH "AUTHORS"
.LP
Univa Support <support@univa.com>
.SH "SEE ALSO"
.LP
get-software-profile(8)
