.\" Copyright 2008-2018 Univa Corporation
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"    http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.

.TH "get-itle-software-profile-list" "8" "7.0" "Univa" "Tortuga"
.SH "NAME"
.LP
get-itle-software-profile-list - Get a list of available idle software profiles.
.SH "SYNTAX"
.LP
\fBget-itle-software-profile-list [options]
.SH "DESCRIPTION"
.LP
The get-itle-software-profile-list returns the list of idle software profiles configured on the system.  An idle software profile is simply a software profile that contains enough functionality for a given hardware profile to be reprovisioned.  For a non-BMC or virtual machine an idle profile typically contains the base Tortuga components.
.LP
.SH "Common Tortuga Options"
.LP
.TP
\fB-h, --help
show this help message and exit.
.TP
\fB-?
show this help message and exit.
.TP
\fB-v
print version and exit.
.TP
\fB-d \fPCONSOLELOGLEVEL\fB, --debug=\fPCONSOLELOGLEVEL
set debug level; valid values are: critical, error, warning, info, debug
.TP
\fB--username=\fPUSERNAME
Credential to use when not running as root on the Installer.
.TP
\fB--password=\fPPASSWORD
Credential to use when not running as root on the Installer.
.\".SH "EXAMPLES"
.\".LP
.SH "AUTHORS"
.LP
Univa Support <support@univa.com>
.SH "SEE ALSO"
.LP
get-software-profile(8)
